/**
 * Auto-generated configuration file
 * Generated at: 2026-01-10T13:59:10.530Z
 * 
 * DO NOT EDIT THIS FILE DIRECTLY if you are using 'inject_env.js' or CI/CD.
 */

window.AppConfig = {
    apiKey: "sk-4b65cd76eada41a5b8d6061446cd50ad",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    model: "qwen-turbo"
};
